"""Read frozen caps from docs/protocol.md (generated by run_pilot.py)."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

PAPER1_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_PROTOCOL_PATH = PAPER1_ROOT / "docs" / "protocol.md"


@dataclass(frozen=True)
class ProtocolCaps:
    loose_batch: float
    tight_batch: float
    n_tasks: int
    pressure_max: float
    pressure_init: float


def _parse_float_table_row(text: str, key: str) -> float | None:
    pattern = rf"^\|\s*{re.escape(key)}\s*\|\s*([0-9.]+)\s*\|"
    match = re.search(pattern, text, flags=re.MULTILINE)
    if not match:
        return None
    return float(match.group(1))


def read_protocol_caps(
    n_tasks: int,
    *,
    path: Path | None = None,
) -> ProtocolCaps:
    protocol_path = path or DEFAULT_PROTOCOL_PATH
    if not protocol_path.is_file():
        raise FileNotFoundError(f"protocol not found: {protocol_path}")

    text = protocol_path.read_text()

    loose_key = f"loose_batch_n{n_tasks}"
    tight_key = f"tight_batch_n{n_tasks}"
    loose = _parse_float_table_row(text, loose_key)
    tight = _parse_float_table_row(text, tight_key)
    if loose is None or tight is None:
        raise ValueError(f"protocol missing batch caps for n={n_tasks} ({loose_key}, {tight_key})")

    pressure_max = _parse_float_table_row(text, "PRESSURE_MAX") or 1.5
    pressure_init = _parse_float_table_row(text, "BUDGET_PRESSURE_INIT") or 0.35
    return ProtocolCaps(
        loose_batch=loose,
        tight_batch=tight,
        n_tasks=n_tasks,
        pressure_max=pressure_max,
        pressure_init=pressure_init,
    )
