"""Step B.0 budget pilot: 3 compare_easy tasks × all_pro (uncapped) → M, batch caps.

Usage:
  cd paper1 && PYTHONPATH=src:../external/mini-swe-agent/src python -m budgetflow.run_pilot

Writes:
  data/runs/pilot_b0.jsonl
  data/runs/pilot_b0_summary.json
  docs/protocol.md  (FROZEN caps — do not edit after compare runs)
"""

from __future__ import annotations

import json
import statistics
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

SRC = Path(__file__).resolve().parents[1]
REPO_ROOT = SRC.parent
MINI_SWE_SRC = REPO_ROOT.parent / "external" / "mini-swe-agent" / "src"
for path in (str(SRC), str(MINI_SWE_SRC)):
    if path not in sys.path:
        sys.path.insert(0, path)

from budgetflow.adapter.runner import run_mini_swe_task  # noqa: E402
from budgetflow.defaults import (  # noqa: E402
    BUDGET_PRESSURE_INIT,
    PRESSURE_MAX,
    TIER1_MODEL,
    TIER2_MODEL,
    TIER3_MODEL,
)
from budgetflow.deepseek_backend import load_env_file  # noqa: E402
from budgetflow.lite_tasks import COMPARE_EASY_INSTANCE_IDS, PILOT_INSTANCE_IDS, load_pilot_tasks  # noqa: E402

RUNS_DIR = REPO_ROOT / "data" / "runs"
PROTOCOL_PATH = REPO_ROOT / "docs" / "protocol.md"
PINNED_COMMIT_PATH = REPO_ROOT.parent / "external" / "PINNED_COMMIT"
UNCAPPED_BUDGET = 1_000_000.0


def _read_pinned_commit() -> str:
    if PINNED_COMMIT_PATH.is_file():
        return PINNED_COMMIT_PATH.read_text().strip()
    mini_swe_dir = REPO_ROOT.parent / "external" / "mini-swe-agent"
    if (mini_swe_dir / ".git").exists():
        import subprocess

        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=mini_swe_dir, text=True).strip()
    return "unknown"


def _batch_caps(m: float, n: int) -> tuple[float, float]:
    return 2.0 * m * n, 0.5 * m * n


def _write_protocol(*, m: float, pilot_records: list[dict]) -> None:
    pinned = _read_pinned_commit()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    pilot_ids = [r["instance_id"] for r in pilot_records]
    compare_ids = list(COMPARE_EASY_INSTANCE_IDS)
    loose_per_task = 2.0 * m
    tight_per_task = 0.5 * m
    loose_n3, tight_n3 = _batch_caps(m, 3)
    loose_n5, tight_n5 = _batch_caps(m, 5)
    costs = [float(r["total_cost"]) for r in pilot_records]
    outlier_note = ""
    if costs and m > 0:
        outliers = [r["instance_id"] for r in pilot_records if float(r["total_cost"]) > 3 * m]
        if outliers:
            outlier_note = f"\nOutlier tasks (>3×M, not excluded): {outliers}\n"

    body = f"""# BudgetFlow frozen experiment protocol

> **status: FROZEN** — generated by `run_pilot.py` at {now}. Do not edit caps after compare runs start.

## Scaffold

| Key | Value |
|---|---|
| mini-SWE-agent commit | `{pinned}` |
| harness | B — `local_harness.py` (Docker unavailable; not directly comparable to public SWE-bench leaderboard) |

## Backend pool

| tier | model_id |
|---|---|
| Tier1 | `{TIER1_MODEL}` |
| Tier2 | `{TIER2_MODEL}` |
| Tier3 | `{TIER3_MODEL}` |

Cost unit: **governor units** (mock token costs in `adapter/backends.py`, same口径 as BF routing runs).

## Budget pilot (B.0)

| Key | Value |
|---|---|
| pilot tasks | {pilot_ids} |
| M (median per-task cost) | {m:.4f} |
| loose_per_task | {loose_per_task:.4f} |
| tight_per_task | {tight_per_task:.4f} |
| loose_batch_n3 | {loose_n3:.4f} |
| tight_batch_n3 | {tight_n3:.4f} |
| loose_batch_n5 | {loose_n5:.4f} |
| tight_batch_n5 | {tight_n5:.4f} |

Per-task formula: `loose = 2 × M`, `tight = 0.5 × M`.  
Batch formula: `loose_batch = 2 × M × n`, `tight_batch = 0.5 × M × n`.
{outlier_note}
## Dynamic budget_pressure (frozen)

| Key | Value |
|---|---|
| BUDGET_PRESSURE_INIT | {BUDGET_PRESSURE_INIT:.4f} |
| PRESSURE_MAX | {PRESSURE_MAX:.4f} |

Formula: `pressure = init + used_frac × (PRESSURE_MAX - init)` where  
`used_frac = (spent_budget + reserved_budget) / total_budget` (0 when uncapped).

## Eval task lists

**Pilot (3):** `{", ".join(pilot_ids)}` (same as `PILOT_INSTANCE_IDS = compare_easy[:3]`)

**Compare easy (5):** `{", ".join(compare_ids)}`

**RQ2 iter-1 (20):** TBD — extend after 5-task pilot gate.

## Strategy entry points

| strategy | module |
|---|---|
| all_pro / no_bf baseline | `run_mini_swe_baseline.py` |
| all_pro (BF-wrapped) | `adapter/runner.py` strategy=`all_pro` |
| budgetflow_full | `adapter/strategies.py` + `adapter/mini_swe_proxy.py` |
| budget_only | `adapter/strategies.py` |
| workflow_level | `adapter/strategies.py` |

## defaults.py

Path: `paper1/src/budgetflow/defaults.py` — `PROGRESS_TABLE`, `W_I`, `BUDGET_PRESSURE_INIT`, `PRESSURE_MAX` frozen (no CLI override).
"""
    PROTOCOL_PATH.parent.mkdir(parents=True, exist_ok=True)
    PROTOCOL_PATH.write_text(body)


def main() -> None:
    load_env_file()
    tasks = load_pilot_tasks(3)
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = RUNS_DIR / "pilot_b0.jsonl"
    summary_path = RUNS_DIR / "pilot_b0_summary.json"

    print(f"pilot B.0: n={len(tasks)} strategy=all_pro uncapped budget", flush=True)
    print(f"tasks={[t.instance_id for t in tasks]}", flush=True)
    records: list[dict] = []
    started = time.time()

    with out_path.open("w") as handle:
        for index, task in enumerate(tasks, start=1):
            print(f"[{index}/{len(tasks)}] START {task.instance_id}", flush=True)
            run_started = time.time()
            result = run_mini_swe_task(
                task,
                strategy="all_pro",
                budget_per_task=UNCAPPED_BUDGET,
            )
            record = {
                "instance_id": result.instance_id,
                "strategy": result.strategy,
                "harness_resolved": result.harness_resolved,
                "total_cost": result.total_cost,
                "llm_turns": result.llm_turns,
                "backend_picks": list(result.backend_picks),
                "exit_status": result.exit_status,
                "detail": result.harness_detail,
                "elapsed_s": round(time.time() - run_started, 1),
            }
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")
            handle.flush()
            records.append(record)
            status = "OK" if result.harness_resolved else "FAIL"
            print(
                f"[{index}/{len(tasks)}] DONE {task.instance_id} {status} "
                f"cost={result.total_cost:.4f} turns={result.llm_turns}",
                flush=True,
            )

    costs = [float(r["total_cost"]) for r in records]
    m = statistics.median(costs) if costs else 0.0
    loose_per_task = 2.0 * m
    tight_per_task = 0.5 * m
    loose_n3, tight_n3 = _batch_caps(m, 3)
    loose_n5, tight_n5 = _batch_caps(m, 5)
    summary = {
        "pilot_task_ids": [t.instance_id for t in tasks],
        "pilot_instance_ids": list(PILOT_INSTANCE_IDS[:3]),
        "costs": costs,
        "M": m,
        "loose_per_task": loose_per_task,
        "tight_per_task": tight_per_task,
        "loose_batch_n3": loose_n3,
        "tight_batch_n3": tight_n3,
        "loose_batch_n5": loose_n5,
        "tight_batch_n5": tight_n5,
        "pressure_max": PRESSURE_MAX,
        "budget_pressure_init": BUDGET_PRESSURE_INIT,
        "elapsed_s": round(time.time() - started, 1),
        "jsonl": str(out_path),
    }
    summary_path.write_text(json.dumps(summary, indent=2) + "\n")
    _write_protocol(m=m, pilot_records=records)

    print(f"\nFINAL M={m:.4f} loose_batch_n5={loose_n5:.4f} tight_batch_n5={tight_n5:.4f} elapsed={summary['elapsed_s']}s")
    print(f"jsonl={out_path}")
    print(f"summary={summary_path}")
    print(f"protocol={PROTOCOL_PATH} (FROZEN)")


if __name__ == "__main__":
    main()
